---
- name: Install Zabbix
  hosts: zabbix
  become: true
  vars:
    pass_zabbixdb: zabbix

  tasks:
    - name: Add Zabbix repository
      shell: wget https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb
      args:
        chdir: /tmp

    - name: Install Zabbix package
      shell: dpkg -i zabbix-release_6.0-4+ubuntu22.04_all.deb
      args:
        chdir: /tmp

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Zabbix packages
      apt:
        name:
          - apache2
          - postgresql
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php8.1-pgsql
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present

    - name: Create user PostgreSQL for Zabbix
      expect:
        command: sudo -u postgres createuser --pwprompt zabbix
        responses:
          (?i).*(Enter password for new role)(.*):
          - '{{ pass_zabbixdb }}'
          (?i).*(Enter it again)(.*):
          - '{{ pass_zabbixdb }}'

    - name: Create database PostgreSQL for Zabbix
      shell: >
        sudo -u postgres createdb -O zabbix zabbix

    - name: Import schema
      shell:
        zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix

    - name: Set DBPassword in Zabbix config
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^DBPassword='
        line: 'DBPassword=zabbix'

    - name: Restart Zabbix
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - apache2
        - zabbix-server
        - zabbix-agent
